version: '3'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data